title: James Ohanka 
logo: Jamesdonuch.jpg 
Description: A data analyst with experience using EXCEL to create automated reports, SQL for data interrogation and manipulation and Power BI for creating business intelligence reports
#show_downloads: true 
#google_analytics: 
theme: Jekyll-theme-minimal
